version: "3"

services:
  nginx:
    image: vglazarev/multi-nginx
    mem_limit: 128m
    ports:
      - "80:80"
  api:
    image: vglazarev/multi-server
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: vglazarev/multi-client
    mem_limit: 128m
  worker:
    image: vglazarev/multi-worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
