name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build -t vglazarev/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true vglazarev/react-test npm test

      - run: docker build -t vglazarev/multi-client ./client
      - run: docker build -t vglazarev/multi-nginx ./nginx
      - run: docker build -t vglazarev/multi-server ./server
      - run: docker build -t vglazarev/multi-worker ./worker

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push vglazarev/multi-client
      - run: docker push vglazarev/multi-nginx
      - run: docker push vglazarev/multi-server
      - run: docker push vglazarev/multi-worker

#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#     Will be populated with actual credentials
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: multi-gh
#          environment_name: Multigh-env
#          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
#          region: us-east-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip